Update main_streamlit-taxi-fare-app.yml

diff --git a/.github/workflows/main_streamlit-taxi-fare-app.yml b/.github/workflows/main_streamlit-taxi-fare-app.yml
--- a/.github/workflows/main_streamlit-taxi-fare-app.yml
+++ b/.github/workflows/main_streamlit-taxi-fare-app.yml
@@ -45,6 +45,11 @@ jobs:
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}
 
+      # Clean up old Docker images (if needed)
+      - name: Clean up old Docker images
+        run: |
+          docker rmi myacrstreamlit.azurecr.io/streamlit-taxi-fare-app:latest || true
+
       # Build and push Docker image
       - name: Build and Push Docker Image
         run: |
